#!/bin/bash

source .env

URL="https://api.openai.com/v1/engines/text-davinci-003/completions"

chat() {
    prompt="$1"
    answer=$(curl -s -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $API_KEY_CHATGPT" -d '{"prompt": "'"$prompt"'", "max_tokens": 150}' $URL)
    text_answer=$(echo $answer | jq -r '.choices[0].text' | sed 's/\"//g')
    echo "$text_answer"
}

chat "$1"

# It doesn't work