#!/usr/bin/bash

cd ~/Documentos/repos/smart-stack-definitions && 
git checkout master && 
git pull && 
ENV=local make deploy-localinstallation && 
docker start smartContent-apache &&
docker start moodle
