#!/usr/bin/bash

if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    echo "Not a Git repository."
    exit 1
fi

file_name=$(git -c color.status=always status --short |
    fzf --height 100% --ansi \
        --preview '(git diff HEAD --color=always -- {-1} | sed 1,4d)' \
        --preview-window right:65% |
    cut -c4- |
    sed 's/.* -> //' |
    tr -d '\n')

if [[ -n $file_name ]]; then
    code --new-window $file_name
else
    echo "You haven't selected any file!"
fi
