- clean: ['~']

- defaults:
    link:
      create: true
      force: true

- create:
      - ~/.z

- link:
    # ~/.bash_profile: shell/bash/.bash_profile
    ~/.bashrc: shell/bash/.bashrc
    # ~/.gitattributes: git/.gitattributes
    ~/.gitconfig: git/.gitconfig
    ~/bin: bin/oh-my-posh
    ~/.config/Code/User: editors/vs-code/User
    # ~/.gitignore_global: git/.gitignore_global
    # ~/.profile: shell/bash/.profile