version: '3.6'

services:
  chatgpt:
    image: ghcr.io/ivanfioravanti/chatbot-ollama:main
    ports:
      - 3005:3000
    environment:
      - DEFAULT_MODEL=llama2
      - OLLAMA_HOST=http://ollama:11434
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./ollama/models:/ollama/models
    environment:
      - OLLAMA_MODELS=/ollama/models

# Run this the first time you build it to download the model
# docker-compose exec ollama ollama pull llama2
